### ISSUE TITLE
Missing option i configuration drop down menu

### ISSUE THREAD

**Issue by ti-guru** [gskjold/AmsToMqttBridge#368] opened 2022-11-29 22:42 UTC
**Describe the bug**
The option "ENTSO-E API" is only available in the drop down menu on the front page. 

**To Reproduce**
1. Go to frontpage
2. Click on "Configuration"
3. Select "Meter", "Wifi", "MQTT", "Web" or "NTP"
4. Click on "Configuration" once more to see that "ENTSO-E API" option is missing in the drop down menu. Same applies to "System". 

**Expected behavior**
The option "ENTSO-E API" should be available in the drop down menu irrespective of page viewed.

**Screenshots**
No. 

**Hardware information:**
 - Country: Norway
 - Meter:  Aidon
 - Encryption enabled no
 - AMS reader: Pow-U ESP32
 - M-bus adapter (if applicable): N/A

**Relevant firmware information:**
 - Version: 2.1.14
 - MQTT: yes
 - MQTT payload type: HA
 - HAN GPIO: GPIO16
 - HAN baud and parity: 8E1
 - Temperature sensors N/A
 - ENTSO-E API enabled: yes

**Comment by gskjold** [comment] 2022-11-30 07:18
Thank you for reporting. Duplicate of #323 which I closed very recently because I have a new version coming up where it will be fixed :)

**Closed** 2022-11-30 07:31 UTC
