### ISSUE TITLE
Transport tarif option

### ISSUE THREAD

**Issue by Allan-Hoejberg** [gskjold/AmsToMqttBridge#313] opened 2022-09-14 10:55 UTC
I Denmark, the price we pay for the Kwh, is based on a transport tarif + the Khw price and vat, so it would be nice to ba able to add a fixed transport tarif to the price

**Comment by gskjold** [comment] 2022-09-14 10:56
Technically duplicate of #252

**Closed by gskjold** 2022-09-14 10:56 UTC
