### ISSUE TITLE
Time based fee addition before multiplier

### ISSUE THREAD

**Issue by svendhoest** [gskjold/AmsToMqttBridge#399] opened 2023-01-10 12:13 UTC
Problem :

I would like to be able to specify an addition to energy price, based on timeslots and months so i can accomodate prices like this :

Months like summer and winter. April -> September, October -> March.
Timeslots like 0 -> 5, 6 -> 16, 17 -> 20, 21 -> 23

Please consider to make it possible to add to energy prices before multiplying ?
The addition needs to be able to be specified for timeslots and months.

Further explanation : https://radiuselnet.dk/wp-content/uploads/fleksibelt-forbrug.png

**Comment by gskjold** [comment] 2023-01-10 12:14
Duplicate of #252

**Closed by gskjold** 2023-01-10 12:14 UTC
